/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The last name
         */
        "last": string;
    }
    interface MyTable {
        "apiUrl": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyTableElement extends Components.MyTable, HTMLStencilElement {
    }
    var HTMLMyTableElement: {
        prototype: HTMLMyTableElement;
        new (): HTMLMyTableElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-table": HTMLMyTableElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The last name
         */
        "last"?: string;
    }
    interface MyTable {
        "apiUrl"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-table": MyTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-table": LocalJSX.MyTable & JSXBase.HTMLAttributes<HTMLMyTableElement>;
        }
    }
}
